# Copyright 2023 XigXog
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: kubefox.xigxog.io/v1alpha1
kind: HTTPAdapter
metadata:
  name: graphql
spec:
  url: http://hasura-{{.Vars.db}}/v1/graphql
  insecureSkipVerify: true
---
apiVersion: kubefox.xigxog.io/v1alpha1
kind: HTTPAdapter
metadata:
  name: hasura
spec:
  url: http://hasura-{{.Vars.db}}/
  insecureSkipVerify: true